sudo: required
language: go
go:
  - "1.12"
go_import_path: github.com/2dust/AndroidLibV2rayLite
git:
  depth: 5
addons:
  apt:
    update: true
before_script:
- sudo ntpdate -u time.google.com
- date
- make all
- make downloadGoMobile
script:
- make BuildMobile
after_success:
deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file:
    - libv2ray.aar
  skip_cleanup: true
  on:
    tags: true
